### ISSUE TITLE
Feature: User can view all created exercises

### ISSUE THREAD

**Issue by KrisMackenroth** [KrisMackenroth/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view all available exercises within the pulled database. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be presented with a page that has all exercises listed downward. Each exercise will have a name, type, and view button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (659)](https://user-images.githubusercontent.com/103297457/180850717-55044636-468f-4889-b672-4ea46d954886.png)
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to match the created schema in DBDesigner
- [ ] Update `data.sql` to match the created data in DBDesigner

### ☁️ Server Tasks

- [ ] Update `server/index.js` to send a get request to the exercises table.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to send a fetch request to the exercises table as well as render them to the page.
- [ ] Update the component to map through the exercises obtained from the exercises table and place them in elements that will be rendered to the page. 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
